defaults:
  - data: debate

model:
  name: text-att
  embed_dim: 768
  num_heads: 12
  dropout: 0.1
  num_classes: 2
  lr: e-3

log:
  dir: "../resource/logs/"

model_checkpoint:
  dir: "../resource/model_checkpoints/"

tasks: ["fit"]

folds: [0, 1, 2, 3, 4]

stats:
  dir: "../resource/stats/"

trainer:
  max_epochs: 3
  patience: 1
  min_delta: 0.01
  fast_dev_run: False